# Generated by Django 6.0.1 on 2026-01-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_employee', '0003_plannings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_departement', models.TextField()),
            ],
        ),
    ]
