# Generated by Django 6.0.1 on 2026-01-27 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_employee', '0004_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='gestion_employee.departement'),
        ),
    ]
