# Generated by Django 6.0.1 on 2026-01-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_employee', '0005_alter_employee_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannings',
            name='heure_retard',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
