# Generated by Django 6.0.1 on 2026-01-28 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_employee', '0006_plannings_heure_retard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.TextField()),
                ('year', models.TextField()),
                ('primes', models.TextField()),
                ('deduction', models.TextField()),
                ('salary_net', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='gestion_employee.employee')),
            ],
        ),
    ]
