# Generated by Django 6.0.1 on 2026-01-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_employee', '0007_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_conge', models.TextField()),
                ('isPaye', models.TextField()),
                ('justification', models.TextField()),
            ],
        ),
    ]
