# Generated by Django 6.0.1 on 2026-01-31 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_employee', '0008_typeconge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeConger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('total_day', models.IntegerField()),
                ('status', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_conges', to='gestion_employee.employee')),
                ('typeconge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='gestion_employee.typeconge')),
            ],
        ),
    ]
